config/routes.rb
Rails.application.routes.draw do
  # ActiveAdminのルートの基本設定
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'
  get 'homes/about'

  # deviseのルート基本設定
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # deviseのルート基本設定
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # usersのルート
  patch 'users/withdraw'
  resources :users, only: %i[show]

  # dreamsのルート
  get 'dreams/top'
  resources :dreams do
    get :search, on: :collection
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  # 問い合わせのルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  # ブラウザバックの連続プッシュなどでページ更新がうまくいかない場合にサイトトップへいくルート設定
  get '*path', controller: 'homes', action: 'top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dream.rb
class Dream < ApplicationRecord
  # user/comments/favoritesをそれぞれアソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # いいねをしているかチェック
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿時にtitle/body/start_timeが空でないかバリデーションチェック
  validates :title, presence: true
  validates :body, presence: true
  validates :start_time, presence: true

  # emotion（感情）の分類
  enum emotion: { 楽しい: 0, 嫌気: 1, 悲しい: 2, 恐い: 3, 怒り: 4 }
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  # トップページ
  def top; end

  # 新規投稿のための箱
  def new
    @dream = Dream.new
  end

  # 新規投稿の作成
  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    if @dream.save
      redirect_to dream_path(@dream.id)
    else
      render :new
    end
  end

  # 投稿一覧ページ（ページャ追加）
  def index
    @dreams = Dream.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  # 投稿の詳細ページ
  def show
    @dream = Dream.find(params[:id])
    @user = @dream.user
    @comment = Comment.new
  end

  # 投稿の編集ページ
  def edit
    @dream = Dream.find(params[:id])
    @user = @dream.user
    # 投稿者でなければ一覧画面へリダイレクト
    redirect_to dreams_path if @dream.user != current_user
  end

  # 投稿内容の更新
  def update
    @dream = Dream.find(params[:id])
    if @dream.update(dream_params)
      redirect_to dream_path(@dream.id)
    else
      @dream = dream
      render :edit
    end
  end

  # 投稿の削除
  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dreams_path
  end

  # 投稿の検索ページ
  def search
    @dreams = if params[:title].present?
                # 投稿のタイトルと部分一致する投稿を検索
                Dream.where('title LIKE ?', "%#{params[:title]}%").order(created_at: :desc).page(params[:page]).per(10)
              else
                Dream.none.page(params[:page]).per(10)
              end
  end

  private

  def dream_params
    params.require(:dream).permit(:user_id, :day, :emotion, :title, :body, :start_time)
  end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_comment.html.erb
<div class="comments">
  <p>コメント件数：<%= dream.comments.count %></p>
  <!--コメント表示-->
  <% dream.comments.each do |comment| %>
    <div id="delete_<%= comment.id %>", class="border">
      <%= comment.user.name %>&emsp;
      <%= comment.created_at.strftime('%Y/%m/%d') %>&emsp;
      <%= comment.comment %>
      <!--コメントしたユーザーなら削除リンクの表示-->
      <% if comment.user == current_user %>
      <div class="comment-delete">
        <%= link_to "削除", dream_comment_path(comment.dream, comment), method: :delete, remote: true %>
      </div>
    </div>
    <% end %>
  <% end %>

</div>

app/views/dreams/_favorites.html.erb
<!--いいね済みなら押したら削除-->
<% if dream.favorited_by?(current_user) %>
  <%= link_to dream_favorites_path(dream), method: :delete, remote: true do %>
    ❤&nbsp;<%= dream.favorites.count %>
  <% end %>
<% else %>
<!--未いいねなら押したらいいねする-->
  <%= link_to dream_favorites_path(dream), method: :post, remote: true do %>
    🖤&nbsp;<%= dream.favorites.count %>
  <% end %>
<% end %>

app/views/dreams/edit.html.erb
<div class="comtainer">

  <div class="row">
    <div class="col-2 mx-auto text-center">
      <h2>夢の内容の編集</h2>
    </div>
  </div>

  <!--新規投稿フォーム-->
  <div class="row">
    <div class="col-10 mx-auto">
    <%= form_with model: @dream, local:true do |f| %>

    <div class="row">
      <div class="col-3 mx-auto text-center">
        <label>夢のタイトル</label>
        <%= f.text_field :title, :size => "30*50" %>
      </div>
    </div>

    <div class="row">
      <div class="col-6 mx-auto text-center">
        <label>夢の内容</label>
        <%= f.text_area :body, :size => "70x5"  %>
      </div>
    </div>

    <div class="row">
      <div class="col-6 mx-auto text-center align-center">
        <label>夢で感じた感情</label><br />
        <label><%= f.radio_button :emotion, "楽しい", :checked => true %>楽しい</label>&ensp;
        <label><%= f.radio_button :emotion, "嫌気" %>嫌気</label>&ensp;
        <label><%= f.radio_button :emotion, "悲しい" %>悲しい</label>&ensp;
        <label><%= f.radio_button :emotion, "恐い" %>恐い</label>&ensp;
        <label><%= f.radio_button :emotion, "怒り" %>怒り</label>
      </div>
    </div>

    <div class="row">
      <div class="col-2 mx-auto text-center">
        <label>夢をみた日</label>
      <%= f.datetime_field :start_time %>
      </div>
    </div>

    <div class="row submit">
      <div class="col-2 mx-auto text-center">
        <%= f.submit "編集完了！" %>
      </div>
    </div>
    <% end %>
    </div>
  </div>

  <div class="row dream-edit">
    <div class="col-2 mx-auto text-center">
      <%= link_to "削除する", dream_path(@dream.id), method: :delete, class:'btn btn-lg btn-danger' %>
    </div>
  </div>

</div>

app/views/dreams/home.html.erb
<div class="image">
  <div class="container">

    <div class="row head">
      <div class="col-5 mx-auto text-center">
        <h2>他人の夢、覗いてみます？</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-5  mx-auto text-center">
        <p class="p">いろんな人の夢、覗いてみませんか？</p>
        <p class="p">普段気にしないけど、他人の夢ってどんななんだろう、、、、</p>
      </div>
    </div>

    <!--お問合せページへのボタン-->
    <div class="row">
      <div class="col-10 mx-auto text-center">
        <%= link_to "お問合せ", inquiry_path, class: "btn btn-sm btn-primary" %>
      </div>
    </div>

  </div>
</div>

app/views/dreams/index.html.erb
<div class="container">

  <!--検索フォーム-->
  <div class="row">
    <div class="col-2.5"><label>夢のタイトルで検索できます</label></div>
    <div class="col-4">
      <%= form_with url: search_dreams_path, method: :get, local: true do |f| %>
        <%= f.text_field :title %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-3 text-center">
      <h2><i class="fas fa-bed"></i>&nbsp;みんなの夢</h2>
    </div>
    <% if user_signed_in? %>
    <div class="col-2">
      <%= link_to "夢の新しい投稿", new_dream_path, class: "btn btn-lg btn-primary" %>
    </div>
    <% end %>
  </div>

  <!--投稿の一覧-->
  <% @dreams.each do |dream| %>
  <div class="container border">
    <div class="row border-bottom align-items-center">
      <div class="col-2">
        <!--プロフィール画像があれば表示-->
        <% if dream.user.image.to_s.present? %>
          <%= image_tag dream.user.image.thumb.to_s, size: "50x50" %>
        <% else %>
          <!--プロフィール画像が無い人に表示させる画像-->
          <%= image_tag "no_image.jpg", size: "50x50" %>
        <% end %>
      <!--ログイン済みなら名前からユーザーページへ-->
      <% if user_signed_in? %>
        <%= link_to user_path(dream.user.id) do %>
          <%= dream.user.name %>
        <% end %>
      <% else %>
      <!--未ログインならリンクは表示しない-->
        <%= dream.user.name %>
      <% end %>
      </div>
      <div class="col-4">
        夢名「&nbsp;
        <!--投稿の詳細へ-->
        <%= link_to dream_path(dream.id) do %>
          <%= dream.title %>
        <% end %>&nbsp;」
      </div>
      <div class="col-2">
        <i class="fas fa-hand-holding-heart"></i> <%= dream.emotion %>
      </div>
      <div class="col-3 text-center"><i class="fas fa-user-clock"></i> <%= dream.start_time.strftime("%Y年%m月%d日") %></div>
    </div>
    <div class="row dream-contents">
      <div class="col-10">
        &nbsp;夢の内容<br />
        <!--内容の表示を100文字までに設定-->
        「&nbsp;<%= dream.body.truncate(100) %>&nbsp;」
      </div>
    </div>

    <div class="row dream-contents">
      <!--ログイン済みならいいねできる-->
      <% if user_signed_in? %>
      <div class="col-1 dream_<%= dream.id %>"><%= render 'dreams/favorites', dream: dream %></div>
      <% else %>
      <!--未ログインならいいね数だけ表示-->
      <div class="col-1">
        <i class="far fa-heart"></i> <%= dream.favorites.count %>
      </div>
      <% end %>
      <div class="col-1"><i class="far fa-comment-alt"></i>
      <!--ログイン済みなら投稿の詳細へ-->
      <% if user_signed_in? %>
        <%= link_to "#{dream.comments.count}", dream_path(dream.id) %>
      <% else %>
        <!--未ログインならコメント件数のみ表示-->
        <%= dream.comments.count %>
      <% end %>
      </div>
    </div>

  </div>
  <% end %>

  <div class="row text-center">
    <%= paginate @dreams %>
  </div>

</div>

app/views/dreams/new.html.erb
<div class="container">

  <!--新規投稿失敗時のエラーメッセージ-->
  <% if @dream.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @dream.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row new-top">
    <div class="col-2 mx-auto text-center">
      <h3>夢の投稿</h3>
    </div>
  </div>

  <!--新規投稿フォーム-->
  <%= form_with model:@dream, url:'/dreams', local:true do |f| %>
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>夢のタイトル</label>
      <%= f.text_field :title, placeholder: "タイトルを入力してください", :size => "30*50" %>
    </div>
  </div>

  <div class="row">
    <div class="col-6 mx-auto text-center">
      <label>夢の内容</label>
      <%= f.text_area :body, placeholder: "内容を入力してください", :size => "70x5"  %>
    </div>
  </div>

  <div class="row">
    <div class="col-6 mx-auto text-center align-center">
      <label>夢で感じた感情</label><br />
      <label><%= f.radio_button :emotion, "楽しい", :checked => true %>楽しい</label>&ensp;
      <label><%= f.radio_button :emotion, "嫌気" %>嫌気</label>&ensp;
      <label><%= f.radio_button :emotion, "悲しい" %>悲しい</label>&ensp;
      <label><%= f.radio_button :emotion, "恐い" %>恐い</label>&ensp;
      <label><%= f.radio_button :emotion, "怒り" %>怒り</label>
    </div>
  </div>

  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>夢をみた日</label>
    <%= f.datetime_field :start_time %>
    </div>
  </div>

  <div class="row submit">
    <div class="col-2 mx-auto text-center">
      <%= f.submit "投稿" %>
    </div>
  </div>
  <% end %>

</div>

app/views/dreams/search.html.erb
<div class="container">

  <!--検索フォーム-->
  <div class="row">
    <div class="col-2.5"><label>夢のタイトルで検索できます</label></div>
    <div class="col-4">
      <%= form_with url: search_dreams_path, method: :get, local: true do |f| %>
        <%= f.text_field :title %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
  </div>

  <div class="row align-items-center">
    <div class="col-3 text-center">
      <h2><i class="fas fa-bed"></i>&nbsp;検索結果</h2>
    </div>
    <% if user_signed_in? %>
    <div class="col-2">
      <%= link_to "夢の新しい投稿", new_dream_path, class: "btn btn-lg btn-primary" %>
    </div>
    <% end %>
  </div>

  <!--投稿の一覧-->
  <% @dreams.each do |dream| %>
  <div class="container border">
    <div class="row border-bottom align-items-center">
      <div class="col-2">
        <!--プロフィール画像があれば表示-->
        <% if dream.user.image.to_s.present? %>
          <%= image_tag dream.user.image.thumb.to_s, size: "50x50" %>
        <% else %>
          <!--プロフィール画像が無い人に表示させる画像-->
          <%= image_tag "no_image.jpg", size: "50x50" %>
        <% end %>
      <!--ログイン済みなら名前からユーザーページへ-->
      <% if user_signed_in? %>
        <%= link_to user_path(dream.user.id) do %>
          <%= dream.user.name %>
        <% end %>
      <% else %>
      <!--未ログインならリンクは表示しない-->
        <%= dream.user.name %>
      <% end %>
      </div>
      <div class="col-4">
        夢名「&nbsp;
        <!--投稿の詳細へ-->
        <%= link_to dream_path(dream.id) do %>
          <%= dream.title %>
        <% end %>&nbsp;」
      </div>
      <div class="col-2">
        <i class="fas fa-hand-holding-heart"></i> <%= dream.emotion %>
      </div>
      <div class="col-3 text-center"><i class="fas fa-user-clock"></i> <%= dream.start_time.strftime("%Y年%m月%d日") %></div>
    </div>
    <div class="row dream-contents">
      <div class="col-10">
        &nbsp;夢の内容<br />
        <!--内容の表示を100文字までに設定-->
        「&nbsp;<%= dream.body.truncate(100) %>&nbsp;」
      </div>
    </div>

    <div class="row dream-contents">
      <!--ログイン済みならいいねできる-->
      <% if user_signed_in? %>
      <div class="col-1 dream_<%= dream.id %>"><%= render 'dreams/favorites', dream: dream %></div>
      <% else %>
      <!--未ログインならいいね数だけ表示-->
      <div class="col-1">
        <i class="far fa-heart"></i> <%= dream.favorites.count %>
      </div>
      <% end %>
      <div class="col-1"><i class="far fa-comment-alt"></i>
      <!--ログイン済みなら投稿の詳細へ-->
      <% if user_signed_in? %>
        <%= link_to "#{dream.comments.count}", dream_path(dream.id) %>
      <% else %>
        <!--未ログインならコメント件数のみ表示-->
        <%= dream.comments.count %>
      <% end %>
      </div>
    </div>

  </div>
  <% end %>

  <div class="row text-center">
    <%= paginate @dreams %>
  </div>

</div>

app/views/dreams/show.html.erb
<div class="container">

  <!--投稿のタイトル-->
  <div class="row align-items-center">
    <div class="col-4 text-center">
      <h2>夢&nbsp;名&nbsp;「&nbsp;<%= @dream.title %>&nbsp;」</h2>
    </div>
    <!--投稿者なら編集ページへのボタンを表示-->
    <% if @user == current_user %>
    <div class="col-2">
      <%= link_to "編集する", edit_dream_path(@dream), class: "btn btn-lg btn-success" %>
    </div>
    <% end %>
  </div>

  <!--投稿の詳細情報-->
  <div class="container border">

    <div class="row border-bottom text-center align-items-center">
      <div class="col-2">
        <!--プロフィール画像があれば表示-->
        <% if @dream.user.image.to_s.present? %>
          <%= image_tag @dream.user.image.thumb.to_s, size: "50x50" %>
        <% else %>
          <!--プロフィール画像が無い人に表示させる画像-->
          <%= image_tag "no_image.jpg", size: "50x50" %>
        <% end %>
      </div>
      <div class="col-2">
        <i class="fas fa-user-tag"></i>ニックネーム<br />
        <!--投稿者ページへのリンク-->
        <%= link_to user_path(@user.id) do %>
          <%= @user.name %>
        <% end %>
      </div>
      <div class="col-2">
        <i class="fas fa-hand-holding-heart"></i>&nbsp;感情<br />
        <%= @dream.emotion %>
      </div>
      <div class="col-3">
        <i class="fas fa-user-clock"></i>&nbsp;夢を見た日<br />
        <%= @dream.start_time.strftime("%Y年%m月%d日") %>
      </div>
      <div class="col-3">
        <i class="fas fa-paper-plane"></i>&nbsp;投稿日<br />
        <%= @dream.created_at.strftime("%Y年%m月%d日") %>
      </div>
    </div>

    <div class="row dream-contents">
      <div class="col-10">&nbsp;夢の内容<br />
        「&nbsp;<%= @dream.body %>&nbsp;」
      </div>
    </div>

  </div>


  <!--いいね表示-->
  <div class="row align-items-center text-center">
    <div class="col-1 dream_<%= @dream.id %>">
      <div class="favorites">
        <%= render 'dreams/favorites', dream: @dream %>&nbsp;
      </div>
    </div>
  </div>

  <!--コメント件数表示-->
  <div class="row show-bottom">
    <div class="col-4 show-contents">
      <%= render 'dreams/comment', dream: @dream, comment: @comment %>
    </div>
    <!--コメント入力フォーム-->
    <div class="col-3">
      <%= form_with model:[@dream, @comment] do |f| %>
        <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", :size => "30*100" %>
        <%= f.submit "送信する" %>
      <% end %>
    </div>
  </div>

</div>

app/views/dreams/top.html.erb
<div class="image">
  <div class="container">

    <div class="row head">
      <div class="col-5 mx-auto text-center">
        <h2 class="dream-top">あなたの夢、共有してみませんか？</h2>
      </div>
    </div>

    <div class="row middle">
      <div class="col-4 mx-auto text-center">
        <h2>普段気にしないけど、他人の夢ってどんななんだろう、、、、</h2>
      </div>
      <div class="col-4 mx-auto text-center">
        <h2>今日、こんな夢見た！</h2>
      </div>
    </div>

    <div class="row middle">
      <div class="col-4 mx-auto text-center">
        <h2>私の夢はいつも冒険ストーリーだな〜。</h2>
      </div>
      <div class="col-4 mx-auto text-center">
        <h2>最近、怖い夢見たなー。</h2>
      </div>
    </div>

    <div class="row middle">
      <div class="col-3 mx-auto text-center">
        <div class="post">
          <%= link_to "投稿する！", new_dream_path %>
        </div>
      </div>
    </div>

    <!--お問合せページへのボタン-->
    <div class="row bottom">
      <div class="col-10 mx-auto text-center">
        <div class="contact">
          <%= link_to "お問合せ", inquiry_path, class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    </div>

  </div>
</div>