config/routes.rb
Rails.application.routes.draw do
  # ActiveAdminのルートの基本設定
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'
  get 'homes/about'

  # deviseのルート基本設定
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # deviseのルート基本設定
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # usersのルート
  patch 'users/withdraw'
  resources :users, only: %i[show]

  # dreamsのルート
  get 'dreams/top'
  resources :dreams do
    get :search, on: :collection
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  # 問い合わせのルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  # ブラウザバックの連続プッシュなどでページ更新がうまくいかない場合にサイトトップへいくルート設定
  get '*path', controller: 'homes', action: 'top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # サイトトップ
  def top; end

  # aboutページ
  def about; end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="container">

  <div class="row about">
    <div class="col-8 mx-auto text-center">
      <h2>このサイトは「夢」を身近に感じるためのサイトです。</h2>
    </div>
  </div>
  <div class="row about-bottom">
    <div class="col-7 mx-auto text-center">
      <p class="about-contents">あなたの寝ているときに見る「夢」を他人と共有し、<br />
      それを積み重ねることにより「夢日記」となるようになっています。</p>
    </div>
  </div>

</div>

app/views/homes/top.html.erb
<div class="main-container">
  <!--ロゴ画像-->
  <div class="row">
    <div class="col-10 mx-auto btn">
      <h1 class="text-center"><span><%= image_tag 'dreamsharing.png', size: "200x200" %></span></h1>
    </div>
  </div>

  <!--中央のコメント-->
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <h3>今日の夢、なんだっけ？</h3>
    </div>
  </div>

  <!--簡単ログインボタン-->
  <div class="row btn-top">
    <div class="col-2.5 mx-auto text-center btn-btn">
      <%= link_to 'ゲストログイン（※ポートフォリオ用）', users_guest_sign_in_path, method: :post %>
    </div>
  </div>

  <!--ログインボタン-->
  <div class="row">
    <div class="col-1 mx-auto text-center btn-btn">
      <%= link_to "ログイン", new_user_session_path %>
    </div>
  </div>

  <!--会員登録ボタン-->
  <div class="row btn-bottom">
    <div class="col-1 mx-auto text-center btn-btn">
      <%= link_to "会員登録", new_user_registration_path %>
    </div>
  </div>

</div>