config/routes.rb
Rails.application.routes.draw do
  # ActiveAdminのルートの基本設定
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'
  get 'homes/about'

  # deviseのルート基本設定
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # deviseのルート基本設定
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # usersのルート
  patch 'users/withdraw'
  resources :users, only: %i[show]

  # dreamsのルート
  get 'dreams/top'
  resources :dreams do
    get :search, on: :collection
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  # 問い合わせのルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  # ブラウザバックの連続プッシュなどでページ更新がうまくいかない場合にサイトトップへいくルート設定
  get '*path', controller: 'homes', action: 'top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # 問い合わせ内容のバリデーションチェック
  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
  validates :message, presence: { message: 'お問合せ内容を入力してください' }
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  # 問い合わせページ
  def index
    @inquiry = Inquiry.new
    render :index
  end

  # 問い合わせ内容の確認ページ
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :confirm
    else
      # NG。入力画面を再表示
      render :index
    end
  end

  # サンクスページ
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.save
    # 問い合わせした方に詳細メールを送信
    InquiryMailer.received_email(@inquiry).deliver
    # 管理者にもメールの詳細を送信
    @admin = Inquiry.new
    @admin.email = ENV['SEND_MAIL']
    InquiryMailer.received_email(@admin).deliver
    # 完了画面を表示
    render action: 'thanks'
  end

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/confirm.html.erb
<div class="container">
  
  <div class="row inquiry-top">
    <div class="col-3 mx-auto text-center">
      <h2>お問い合わせ</h2>
    </div>
  </div>

  <!--問い合わせ確認フォーム-->
  <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
  <div class="row inquiry-top">
    <div class="col-3 mx-auto text-center">
      <label>名前</label>
        <%= f.hidden_field :name %>
        <div class="inquiry-field"><%= @inquiry.name %></div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>メールアドレス</label>
        <%= f.hidden_field :email %>
        <div class="inquiry-field"><%= @inquiry.email %></div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>お問い合わせ内容</label>
        <%= f.hidden_field :message %>
        <div class="inquiry-field"><%= simple_format(@inquiry.message) %></div>
    </div>
  </div>
  
  <div class="row inquiry-bottom">
    <div class="col-3 mx-auto text-center">
      <%= f.submit '送信', class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
  
  <% end %>

</div>

app/views/inquiry/index.html.erb
<div class="container">

  <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <div class="row inquiry-top">
    <div class="col-3 mx-auto text-center">
      <h2>お問い合わせ</h2>
    </div>
  </div>

    <!--入力内容のエラー表示-->
  <% if @inquiry.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <strong>入力内容にエラーがあります</strong>
    <ul>
      <% @inquiry.errors.each do |attr, msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <!--問い合わせ内容入力フォーム-->
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>名前<span class="text-danger">（必須）</span></label>
      <td><%= f.text_field :name %></td>
    </div>
  </div>
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>メールアドレス<span class="text-danger">（必須）</spa></label>
      <td><%= f.text_field :email %></td>
    </div>
  </div>
  <div class="row">
    <div class="col-3 mx-auto text-center">
      <label>お問い合わせ内容</label>
      <td><%= f.text_area :message %></td>
    </div>
  </div>
  <div class="row inquiry-bottom">
    <div class="col-3 mx-auto text-center">
      <%= f.submit '確認する', class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
  <% end %>

</div>

app/views/inquiry/thanks.html.erb
<div class="container">

  <div class="row thanks-top">
    <div class="col-4 mx-auto text-center">
      <h2>お問い合わせ</h2>
    </div>
  </div>

  <div class="row thanks-bottom">
    <div class="col-6 mx-auto text-center">
      <p class="inquiry-p">お問い合わせいただきありがとうございました。</p>
    </div>
  </div>

</div>