config/routes.rb
Rails.application.routes.draw do
  # ActiveAdminのルートの基本設定
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'homes#top'
  get 'homes/about'

  # deviseのルート基本設定
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  # deviseのルート基本設定
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    get 'sign_out', to: 'users/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # usersのルート
  patch 'users/withdraw'
  resources :users, only: %i[show]

  # dreamsのルート
  get 'dreams/top'
  resources :dreams do
    get :search, on: :collection
    resource :favorites, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end

  # 問い合わせのルート
  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  # ブラウザバックの連続プッシュなどでページ更新がうまくいかない場合にサイトトップへいくルート設定
  get '*path', controller: 'homes', action: 'top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # ActiveAdminの設定
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # user/dreamのアソシエーション
  belongs_to :user
  belongs_to :dream

  # コメント内容をバリデーションチェック
  validates :comment, presence: true
end

app/models/dream.rb
class Dream < ApplicationRecord
  # user/comments/favoritesをそれぞれアソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # いいねをしているかチェック
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿時にtitle/body/start_timeが空でないかバリデーションチェック
  validates :title, presence: true
  validates :body, presence: true
  validates :start_time, presence: true

  # emotion（感情）の分類
  enum emotion: { 楽しい: 0, 嫌気: 1, 悲しい: 2, 恐い: 3, 怒り: 4 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # user/dreamのアソシエーション
  belongs_to :user
  belongs_to :dream
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  # 問い合わせ内容のバリデーションチェック
  validates :name, presence: { message: '名前を入力してください' }
  validates :email, presence: { message: 'メールアドレスを入力してください' }
  validates :message, presence: { message: 'お問合せ内容を入力してください' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # deviseの基本設定（:authentication_keys => [:name]を追加し、nameでログインできる設定）
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, authentication_keys: [:name]

  # 新規登録時nameも必須にするためバリデーションチェック
  validates :name, presence: true

  # 名前に一意性を持たせる
  validates_uniqueness_of :name

  # ゲストがパスワードを変更できない設定
  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # carrierwaveでの画像アップロード設定
  mount_uploader :image, ImageUploader

  # dreams/comments/favoritesをそれぞれアソシエーション
  has_many :dreams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントの新規作成
  def create
    @dream = Dream.find(params[:dream_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.dream_id = @dream.id
    @comment.save
    @comments = @dream.comments
    @user = @dream.user
  end

  # コメントの削除
  def destroy
    Comment.find_by(id: params[:id], dream_id: params[:dream_id]).destroy
    @dream = Dream.find(params[:dream_id])
    @comments = @dream.comments
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :dream_id, :user_id, :comment)
  end
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  # トップページ
  def top; end

  # 新規投稿のための箱
  def new
    @dream = Dream.new
  end

  # 新規投稿の作成
  def create
    @dream = Dream.new(dream_params)
    @dream.user_id = current_user.id
    if @dream.save
      redirect_to dream_path(@dream.id)
    else
      render :new
    end
  end

  # 投稿一覧ページ（ページャ追加）
  def index
    @dreams = Dream.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  # 投稿の詳細ページ
  def show
    @dream = Dream.find(params[:id])
    @user = @dream.user
    @comment = Comment.new
  end

  # 投稿の編集ページ
  def edit
    @dream = Dream.find(params[:id])
    @user = @dream.user
    # 投稿者でなければ一覧画面へリダイレクト
    redirect_to dreams_path if @dream.user != current_user
  end

  # 投稿内容の更新
  def update
    @dream = Dream.find(params[:id])
    if @dream.update(dream_params)
      redirect_to dream_path(@dream.id)
    else
      @dream = dream
      render :edit
    end
  end

  # 投稿の削除
  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dreams_path
  end

  # 投稿の検索ページ
  def search
    @dreams = if params[:title].present?
                # 投稿のタイトルと部分一致する投稿を検索
                Dream.where('title LIKE ?', "%#{params[:title]}%").order(created_at: :desc).page(params[:page]).per(10)
              else
                Dream.none.page(params[:page]).per(10)
              end
  end

  private

  def dream_params
    params.require(:dream).permit(:user_id, :day, :emotion, :title, :body, :start_time)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # いいね作成
  def create
    @dream = Dream.find(params[:dream_id])
    favorite = current_user.favorites.new(dream_id: @dream.id)
    favorite.save
  end

  # いいねの削除
  def destroy
    @dream = Dream.find(params[:dream_id])
    favorite = current_user.favorites.find_by(dream_id: @dream.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # サイトトップ
  def top; end

  # aboutページ
  def about; end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  # 問い合わせページ
  def index
    @inquiry = Inquiry.new
    render :index
  end

  # 問い合わせ内容の確認ページ
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :email, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render :confirm
    else
      # NG。入力画面を再表示
      render :index
    end
  end

  # サンクスページ
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.save
    # 問い合わせした方に詳細メールを送信
    InquiryMailer.received_email(@inquiry).deliver
    # 管理者にもメールの詳細を送信
    @admin = Inquiry.new
    @admin.email = ENV['SEND_MAIL']
    InquiryMailer.received_email(@admin).deliver
    # 完了画面を表示
    render action: 'thanks'
  end

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # マイページ
  def show
    @user = current_user
    @user = User.find(params[:id])
    @dreams = @user.dreams
  end

  # 退会ページ
  def withdraw; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_logind_header.html.erb
<!--ログイン済みユーザーのヘッダー-->
<span class="navbar-text">ようこそ、<%= current_user.name %>さん</span>
<form class="form-inline">
  <!--ホームページへのリンク-->
  <li class="nav-item"><%= link_to "HOME", dreams_top_path %></li>
  <!--マイページへのリンク-->
  <li class="nav-item"><%= link_to "マイページ", user_path(current_user.id) %></li>
  <!--投稿一覧へのリンク-->
  <li class="nav-item"><%= link_to "みんなの夢一覧", dreams_path %></li>
  <!--ログアウトするリンク-->
  <li class="nav-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
</form>

app/views/layouts/_notlogind_header.html.erb
<!--未ログインユーザーのヘッダー-->
<form class="form-inline">
  <!--aboutページへのリンク-->
  <li class="nav-item"><%= link_to "about", homes_about_path %></li>
  <!--投稿一覧へのリンク-->
  <li class="nav-item"><%= link_to "みんなの夢一覧", dreams_path %></li>
  <!--新規会員登録へのリンク-->
  <li class="nav-item"><%= link_to "新規会員登録", new_user_registration_path %></li>
  <!--ログインへのリンク-->
  <li class="nav-item"><%= link_to "ログイン", new_user_session_path %></li>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DreamSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-dark">
      <div class="container">
        <%= link_to(root_path(), class: 'navbar-brand') do %>
          <%= image_tag 'dreamsharing.png', size: "50x50" %>
        <% end %>
        <ul class="navbar-nav">
        <!--ログイン済みなら-->
        <% if user_signed_in? %>
          <%= render 'layouts/logind_header' %>
        <% else %>
          <!--未ログインなら-->
          <%= render 'layouts/notlogind_header' %>
        <% end %>
        </ul>
      </div>
    </nav>

    <!--表示されるビュー-->
    <div class="image">
      <%= notice %>
      <%= alert %>
      <%= yield %>
    </div>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>© 2021 zunema Inc. ALL Rights Reserved.</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>日曜日</th>
        <th>月曜日</th>
        <th>火曜日</th>
        <th>水曜日</th>
        <th>木曜日</th>
        <th>金曜日</th>
        <th>土曜日</th>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>